### ISSUE TITLE
Has the initial Maintainer window closed?

### ISSUE THREAD

**Issue by lukehinds** [openvex/community#10]
Only heard of OpenVEX today, has the window closed for initial maintainers?

**Comment by dlorenc** [comment]
Hey!

Sorry, I didn't have notifications turned on for this repo :(

The initial maintainer window is closed, but you can follow the defined process here to suggest new ones: https://github.com/openvex/community/blob/main/GOVERNANCE.md

Also note that we've proposed donating the specification to the OSSF here: https://github.com/ossf/wg-vulnerability-disclosures/issues/125
