### ISSUE TITLE
OPEV: Expansion of the VEX Product Field

### ISSUE THREAD

**Issue by puerco** [openvex/community#14]
# OPEV #0014: Expansion of the VEX Product Field

## 🖊️ Enhancement Overview

Six months after the introduction of OpenVEX, the initial integrations and 
community feedback on the initial spec has pointed out several areas where
the product field can be improved to more accurately model the initial use
cases of OpenVEX.

This OPEV proposes reworking the VEX product to become a full object with a new
context called `Component`that lets us introduce new data fields needed today by
the community while letting us more easily add other data in the future.

## 🧑‍💻 Enhancement Proposal Authors

- @puerco

## 👩‍🔧 Sponsoring Maintainers

(not required)

## 📋 OpenVEX Projects

- openvex/spec
- openvex/go-vex
- openvex/vexctl

## 📐 Specs and Documents

Pull Request Open: https://github.com/openvex/community/pull/16 

## ❓ Enhancement Questions

Does this enhancement propose a change to the OpenVEX project's governance
structure?

**NO**

Does this enhancement propose a breaking change with the upstream VEX design
established by the VEX Working Group?

 **NO**

## 💬 Discussion Start Date:

OPEVs shall be discussed for no longer than 30 days after which the vote tally
will be computed and the proposal will either merge or be rejected. 

**Start Date: 2023-07-09**

## 🗳️ Voting Results

Final Enhancement Vote Tally:

👍 : 3 Votes @lumjjb @wagoodman @puerco (implicit) | non binding: @SecurityCRob 

👎 : 0 Votes

**Result:** __`APPROVED`__ 

----

## ℹ️ Voting Instructions: 

To vote for this enhancement, maintainers should add a comment with a 👍 emoji
to show support or 👎 to reject the enhancement.  After voting is over (usually 
after 30 days), votes will be computed by the project's maintainers and
registered in this issue. Refer to  [GOVERNANCE.md](GOVERNANCE.md) for details
on how many votes are required to approve and when voting ends.

**Comment by lumjjb** [comment]
👍 LGTM

**Comment by SecurityCRob** [comment]
While not a voting member, I agree with and endorse this update.  I think this helps set us up for success as we start to see openvex used more broadly.

**Comment by wagoodman** [comment]
after chatting through some of the details offline with @puerco  I'm ultimately a 👍  vote, but there is one incoming change to tweak a `should` to a `must`.

**Comment by puerco** [comment]
@wagoodman: SHOUD/MUST is now addressesd in e200f4af63f97822655c84f262c54276223119d8 , thanks!
